version: "0.0.1"

def:
  iter: [ a, b, c ]


stage:
  sg1:
    step:
      sp1:
        action: iter_map
        args:
          iter:
            arr:
              $ref: def.iter
            enum: idx,item
          map:
            action: echo
            args:
              content:
                - idx: "0-{{idx}}"
                  item: "0-{{item}}"
                
                - idx: "1-{{idx}}"
                  item: "1-{{item}}"
        assert: |
          (all
            (eq curr.state "Ok")
            (eq curr.value.2.1.item "1-c")
          )
      
      sp2:
        action: iter_flatten
        args:
          iter:
            arr:
              $ref: step.sp1.value
        assert: |
          (all
            (eq curr.state "Ok")
            (eq curr.value.5.idx "1-2")
            (eq curr.value.5.item "1-c")
          )
      
      
      sp3:
        action: log
        args:
          content:
            $ref: step.sp2.value
            
            
            
                    
        
