version: '3.5'

services:

  mongodb:
    container_name: mongodb
    image: mongo:4.2.14
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  elasticsearch:
    container_name: elasticsearch
    image: bitranger/elasticsearch:ik-7.12.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200

  chord-cmd:
    container_name: chord-cmd
    image: chord:1
    build:
      context: ..
      dockerfile: github.Dockerfile
    ports:
      - "9999:9999"
    depends_on:
      - elasticsearch
      - mongodb
    command:
      - ./chord-cmd
      - -i/data/chord/job/input
      - -o/data/chord/job/output

  chord-web:
    container_name: chord-web
    image: chord:1
    build:
      context: ..
      dockerfile: github.Dockerfile
    ports:
      - "9999:9999"
    depends_on:
      - chord-cmd
    command: ./chord-web



