version: '3.5'

services:
    
    
    elasticsearch:
        container_name: elasticsearch
        image: bitranger/elasticsearch:ik-7.12.1
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
            - "9300:9300"
        healthcheck:
            test: [ "CMD", "curl", "http://localhost:9200" ]
            interval: 1m30s
            timeout: 10s
            retries: 3

    mysql:
        container_name: mysql
        image: mysql
        ports:
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example

    redis:
        container_name: redis
        image: redis
        ports:
            - 6379:6379

    chord:
        container_name: chord
        image: chord
        build:
            context: ..
            dockerfile: github.Dockerfile
        volumes:
            - ../zero/devops/chord:/data/chord
        ports:
            - "9999:9999"
        depends_on:
            - elasticsearch
            - mysql
            - redis
        command: ./chord-web
        healthcheck:
            test: [ "CMD", "curl", "http://localhost:9999" ]
            interval: 1m30s
            timeout: 10s
            retries: 3




