[workspace]
members = [
    'util',
    'chord',
    'flow',
    'input',
    'output',
    'action',
    'cli',
    'web',
    'zero/test/cdylib_example'
]





[profile.dev]
opt-level = 0

[profile.release]
#panic = 'abort'

