[workspace]
members = [
    'common',
    'flow',
    'input',
    'output',
    'step',
    'cmd',
    'web',
    "zero/step-dylib"
]





[profile.dev]
opt-level = 0

[profile.release]
#panic = 'abort'

