[workspace]
members = [
    'util',
    'chord',
    'flow',
    'input',
    'output',
    'action',
    'cmd',
    'web',
    'zero/action/dylib_example'
]





[profile.dev]
opt-level = 0

[profile.release]
#panic = 'abort'

