version: '3.5'

services:
    
    elasticsearch:
        container_name: elasticsearch
        image: bitranger/elasticsearch:ik-7.12.1
        environment:
            - discovery.type=single-node
        networks:
            - chord
        ports:
            - "9200:9200"
            - "9300:9300"
        healthcheck:
            test: [ "CMD", "curl", "http://localhost:9200" ]
            interval: 1m30s
            timeout: 10s
            retries: 3
    
    mysql:
        container_name: mysql
        image: mysql
        networks:
            - chord
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
    
    redis:
        container_name: redis
        image: redis
        networks:
            - chord
        ports:
            - "6379:6379"


networks:
    chord:
        external: true
