version: '3.5'

services:
    
    elasticsearch:
        container_name: elasticsearch
        image: bitranger/elasticsearch:ik-7.12.1
        environment:
            - discovery.type=single-node
        ports:
            - 9200:9200

