version: '3.5'

services:
  web:
    container_name: chord-web
    build: .
    ports:
      - "9999:9999"

  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
