version: "0.0.1"

stage:
    stage1:
        
        step:
            step1:
                action: lua
                args:
                    code: |
                        for i = 1, 5 do
                            n = math.random(100)
                            print("hello lua: " .. tostring(n));
                        end
                        
                        return
                        {
                             {
                                ['foo'] = {{case.foo}}
                            }
                            ,
                            {
                                ['bar'] = {{case.bar}}
                            }
                        }
                
                assert: |
                    (all
                        (eq curr.value.2.bar (num case.bar))
                    )
            
            step2:
                action: lua
                args:
                    global:
                        arr1: [ "a", "b" ]
                        arr2: {
                            "foo": "bar"
                        }
                    code: |
                        table.insert(arr1, "c");
                        table.insert(arr1, arr2);
                        return arr1;
                assert: |
                    (all
                        (eq curr.value.2 "b")
                        (eq curr.value.3 "c")
                        (eq curr.value.4.foo "bar")
                    )

