version: "0.0.1"

stage:
    stage1:
        
        step:
            step1:
                action: lua
                args:
                    code: |
                        for i = 1, 5 do
                            n = math.random(100)
                            print("hello lua: " .. tostring(n));
                        end
    
                        return
                        {
                             {
                                ['foo'] = {{case.foo}}
                            }
                            ,
                            {
                                ['bar'] = {{case.bar}}
                            }
                        }
                
                assert: |
                    (all
                        (eq curr.value.2.bar (num case.bar))
                    )
                    



