server:
    port: 8080


log:
    level:
        root: debug
        handlebars: info

case:
    batch:
        size: 1

report:
    mongodb:
        url: mongodb://root:example@localhost:27017/admin?retryWrites=true&w=majority