version: "0.0.1"

stage:
    benchmark1:
    
        step:
            docker1:
                action: docker
                timeout: 10
                args:
                    image: "curlimages/curl"
                    cmd:
                        - echo
                        - |-
                            {    "size": 100,    "from": 0,    "sort": {        "elapse": {            "order": "desc"        }    },    "query": {        "bool": {            "must": [                {                    "term": {                        "layer": "case"                    }                }            ]        }    }}
                assert: |+
                    (eq curr.value.size 100)
                


