version: "0.0.1"

def:
    iter: [ a, b, c ]


stage:
    sg1:
        step:
            sp1:
                action: iter_map
                args:
                    iter:
                        arr:
                            $ref: def.iter
                        enum: idx,item
                    
                    map:
                        action: echo
                        args:
                            content:
                                idx: "{{idx}}"
                                item: "{{item}}"
                
                assert: |
                    (all
                        (eq step.sp1.value.2.item "c")
                    )
            
            sp2:
                action: iter_map
                args:
                    iter:
                        arr:
                            $ref: step.sp1.value
                        enum: idx,item
                    
                    map:
                        action: log
                        args:
                            content:
                                idx: "{{idx}}"
                                item:
                                    $ref: item
                    
        
