version: "0.0.1"

stage:
    benchmark1:
        concurrency: 10
        step:
            sleep_example:
                action: sleep
                args:
                    duration: "{{case.seconds}}"
                assert: |+
                    (all
                       (eq 1 1)
                       (eq 2 2)
                       (eq 3 3)
                    )


