[package]
name = "point"
version = "0.1.0"
authors = ["bit-ranger <sincerebravefight@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surf = "2.1.0"
md5 = "0.7.0"
async-std = {version = "1.9.0", features = ["std", "attributes", "tokio1"]}
common = {path = "../common"}