server:
    port: 9999


log:
    level:
        root: warn
        chord: trace

report:
    elasticsearch:
        url: http://127.0.0.1:9200


action:
    download:
        enable: true
        workdir: /data/chord/workdir
    
    fstore:
        enable: true
        workdir: /data/chord/workdir
    
    lua:
        enable: true
