server:
    port: 9999


log:
    level:
        root: warn
        chord: trace

report:
    elasticsearch:
        url: http://127.0.0.1:9200


action:
    download:
        enable: true
        workdir: /data/chord/workdir
    
    fstore:
        enable: true
        workdir: /data/chord/workdir
    
    lua:
        enable: true
    
    dubbo:
        enable: true
        registry:
            protocol: zookeeper
            address: zookeeper://127.0.0.1:2181
        gateway:
            args:
                - "-Ddubbo.application.qos.enable=false"
                - "-jar"
                - /data/chord/bin/dubbo-generic-gateway-0.0.1-SNAPSHOT.jar
                - "--server.port=8085"
