server:
    port: 9999


log:
    level:
        root: warn
        chord: trace

report:
    csv:
        dir: /data/chord/job/output


action:
    download:
        enable: true
        workdir: /data/chord/workdir
    
    fstore:
        enable: true
        workdir: /data/chord/workdir

    lua:
        enable: true
    
    dubbo:
        enable: true
        mode: gateway
        gateway:
            registry:
                protocol: zookeeper
                address: zookeeper://127.0.0.1:2181
            args:
                - "-Ddubbo.application.qos.enable=false"
                - "-jar"
                - /data/chord/conf/dubbo-generic-gateway-0.0.1-SNAPSHOT.jar
                - "--server.port=8085"
