version: "0.0.1"

stage:
    stage1:
        concurrency: 10
        step:
            step1:
                action: python
                args:
                    code: |
                        {"k": [ 
                                obj["foo"], 
                                float(obj["bar"]), 
                                obj["foo"]+obj["bar"], 
                                int(obj["foo"]) + float(obj["bar"])
                              ]
                        }
                    vars:
                        obj:
                            foo: "{{case.foo}}"
                            bar: "{{case.bar}}"
        
                assert:
                    (all
                    (eq curr.value.k ["1", 2.3, "12.3", 3.3])
                    (eq curr.value.k.2 "12.3")
                    (eq curr.value.k.3 3.3)
                    )
                    



