name: ci

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

env:
    CARGO_TERM_COLOR: always

jobs:
    docker:
        
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            
            -   name: Boot services
                run: docker-compose -f zero/devops/docker-compose.yml up -d
            
            -   name: Show services
                run: docker container ls -a
            
            -   name: Inspect elasticsearch
                run: docker inspect elasticsearch
            
            -   name: Test elasticsearch
                run: docker run --network container:elasticsearch appropriate/curl -s --retry 10 --retry-connrefused http://127.0.0.1:9200/
            
            -   name: Test chord-web
                run: docker run --network container:chord appropriate/curl -s --retry 10 --retry-connrefused http://127.0.0.1:9999/
            
            -   name: Test chord-cmd
                run: docker run -v zero/devops/chord:/data/chord chord chord-cmd -i/data/chord/job/input -o/data/chord/job/output
    
    macos:
        
        runs-on: macos-latest
        
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            
            -   name: Build
                run: cargo build --verbose --release
            
            -   name: Upload
                uses: actions/upload-artifact@v2
                with:
                    name: macos-release
                    retention-days: 1
                    if-no-files-found: error
                    path: |
                        target/release/chord-cmd
                        target/release/chord-web
