name: docker-cargo

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Boot services
                run: docker-compose -f .github/docker-compose.yml up -d
            -   name: Show services
                run: docker container ls -a
            -   name: Inspect elasticsearch
                run: docker inspect elasticsearch
            -   name: Test elasticsearch
                run: docker run --network container:elasticsearch appropriate/curl -s --retry 10 --retry-connrefused http://127.0.0.1:9200/
