name: docker-cargo

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        
        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Boot services
                run: docker-compose -f .github/docker-compose.yml up -d
            -   name: Check chord-web health
                run: docker run --network container:chord appropriate/curl -s --retry 10 --retry-connrefused http://127.0.0.1:9999/
            -   name: Check services
                run: docker container ls -a
            -   name: Test chord-cmd
                run: docker exec chord /bin/sh -c "./chord-cmd -i/data/chord/job/input -o/data/chord/job/output"
