name: master

on:
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-20.04
    
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: env-prepare
        run: |
          systemctl status docker
          echo "------------------------------------------------"
          sudo rm /etc/docker/daemon.json
          sudo cp .github/docker/daemon.json /etc/docker/daemon.json
          sudo mkdir -p /etc/systemd/system/docker.service.d
          sudo cp .github/docker/override.conf /etc/systemd/system/docker.service.d/override.conf
          sudo systemctl daemon-reload
          echo "------------------------------------------------"
          sudo systemctl restart docker.service
          sleep 5
          docker info
          echo "------------------------------------------------"
          mkdir -p $HOME/.chord
          cp -r $PWD/zero/devops/chord/conf $HOME/.chord/
          mkdir -p $HOME/.chord/lib
          mkdir -p $HOME/.chord/output
          find $HOME/.chord/
          echo "------------------------------------------------"
          sudo apt-get update
          sudo apt-get install curl
          rustup update

      - name: task-build
        run: |
          cd .chord
          npm install
          npm run build

      - name: service-boot
        run: |
          docker-compose -f docker-compose.yml up -d
          sleep 30
          curl -X GET "http://127.0.0.1:9200/_cat/indices?v"

      - name: dubbo-build
        run: |
          cd action/src/action/dubbo/generic-gateway
          mvn package
          cp target/dubbo-generic-gateway-0.0.1-SNAPSHOT.jar $HOME/.chord/lib/dubbo-generic-gateway-0.0.1-SNAPSHOT.jar
          cd ../../../../..
          pwd
          echo "------------------------------------------------"
          cd zero/test/dubbo_provider
          mvn package
          java -jar target/dubbo-provider-0.0.1-SNAPSHOT.jar &
          sleep 10
          cd ../../..
          pwd
          echo "------------------------------------------------"



      - name: chord-build-cache
        uses: actions/cache@v2
        with:
          key: build-target-linux-gnu-${{ hashFiles('Cargo.lock') }}
          path: |
            ./target

      - name: chord-build
        run: |
          chmod -R 777 $PWD
          make -C .chord/src/cdylib/cdylib_example/bin
          cargo --version
          cargo test  --all-features --verbose --release
          cargo build --all-features --verbose --release
          cargo build --verbose --release
          find $(pwd)

      - name: chord-test
        run: |
          ./target/release/chord run -i$PWD/.chord/dist
      
      
      - name: chord-target-upload
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-unknown-linux-gnu
          retention-days: 7
          if-no-files-found: error
          path: |
            target/release/chord
            target/release/chord-web
            
      - name: extra-lib-upload
        uses: actions/upload-artifact@v2
        with:
          name: extra
          retention-days: 7
          if-no-files-found: error
          path: |
            action/src/action/dubbo/generic-gateway/target/dubbo-generic-gateway-0.0.1-SNAPSHOT.jar
  
  
  windows:
    runs-on: windows-2022
    
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: env-prepare
        run: |
          rustup update
      
      - name: chord-build-cache
        uses: actions/cache@v2
        with:
          key: build-target-windows-msvc-${{ hashFiles('Cargo.lock') }}
          path: |
            ./target
      
      - name: chord-build
        run: |
          cargo build --all-features --verbose --release
          cargo build --verbose --release
      
      - name: chord-target-upload
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-pc-windows-msvc
          retention-days: 7
          if-no-files-found: error
          path: |
            target/release/chord.exe
            target/release/chord-web.exe
  
  macos:
    runs-on: macos-11
    
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: env-prepare
        run: |
          rustup update
      
      - name: chord-build-cache
        uses: actions/cache@v2
        with:
          key: build-target-apple-darwin--${{ hashFiles('Cargo.lock') }}
          path: |
            ./target
      
      - name: chord-build
        run: |
          cargo build --all-features --verbose --release
          cargo build --verbose --release
      
      - name: chord-target-upload
        uses: actions/upload-artifact@v2
        with:
          name: x86_64-apple-darwin
          retention-days: 7
          if-no-files-found: error
          path: |
            target/release/chord
            target/release/chord-web
