name: multi

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

env:
    CARGO_TERM_COLOR: always

jobs:
    linux:
        runs-on: ubuntu-latest
        
        steps:
            -   name: checkout
                uses: actions/checkout@v2
            
            -   name: init
                run: |
                    sudo ls /data
                    sudo cp -r $PWD/zero/devops /data
                    sudo ls /data
                    sudo apt-get update
                    sudo apt-get install curl
                    sudo chmod 777 -R zero
                    
            
            -   name: build
                run: |
                    cargo --version
                    cargo build --verbose --release
                    cargo test  --verbose --release
                    
            
                    
            -   name: compose-boot
                run: |
                    docker-compose -f docker-compose.yml up -d
                    sleep 30
                    
            
            -   name: compose-test
                run: curl http://127.0.0.1:9200/


            -   name: cmd-test
                run: ./target/release/chord-cmd  -i/data/chord/job/input -o/data/chord/job/output
            
            
            -   name: web-boot
                run: |
                    ./target/release/chord-web &
                    sleep 10
                    
            
            -   name: web-test
                run: |
                    curl -X POST --location "http://127.0.0.1:9999/job/exec/"  -H  "Content-Type: application/json" -d "{ \"git_url\": \"git@github.com:bit-ranger/chord.git\", \"branch\": \"master\"  }"
                    sleep 30
                    
            
            -   name: web-report
                run: |
                    curl -X GET --location "http://127.0.0.1:9200/chord@bit-ranger@github.com/_search" \
                        -H "Content-Type: application/json" \
                        -d "{
                            \"query\": {
                                  \"match\": {
                                        \"layer\": \"task\"
                                  }
                            }
                            }"
                    
            -   name: upload
                uses: actions/upload-artifact@v2
                with:
                    name: linux-release
                    retention-days: 1
                    if-no-files-found: error
                    path: |
                        target/release/chord-cmd
                        target/release/chord-web
    
    
    
    docker:
        needs: linux
        runs-on: ubuntu-latest
        
        steps:
            -   name: checkout
                uses: actions/checkout@v2

            -   name: build
                run: docker build -f github.Dockerfile -t chord .
            

    
    windows:
        needs: linux
        runs-on: windows-latest
        
        steps:
            -   name: checkout
                uses: actions/checkout@v2
            
            -   name: build
                run: cargo build --verbose --release
            
            -   name: upload
                uses: actions/upload-artifact@v2
                with:
                    name: windows-release
                    retention-days: 1
                    if-no-files-found: error
                    path: |
                        target/release/chord-cmd.exe
                        target/release/chord-web.exe
    
    macos:
        needs: linux
        runs-on: macos-latest
        
        steps:
            -   name: checkout
                uses: actions/checkout@v2
            
            -   name: build
                run: cargo build --verbose --release
            
            -   name: upload
                uses: actions/upload-artifact@v2
                with:
                    name: macos-release
                    retention-days: 1
                    if-no-files-found: error
                    path: |
                        target/release/chord-cmd
                        target/release/chord-web
