name: multi

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

env:
    CARGO_TERM_COLOR: always

jobs:
    docker:
        runs-on: ubuntu-latest
        
        steps:
            -   name: checkout
                uses: actions/checkout@v2
                
            -   name: init
                run: |
                    sudo apt-get update
                    sudo apt-get install curl
                    sudo chmod 777 -R zero

            -   name: build
                run: docker build -f github.Dockerfile -t chord .

            -   name: compose-boot
                run: docker-compose -f docker-compose.yml up -d

            -   name: compose-wait
                run: |
                    sleep 30

            -   name: es-test
                run: curl http://127.0.0.1:9200/
        
            -   name: chord-cmd-test
                run: docker run --rm -v $PWD/zero/devops/chord:/data/chord chord ./chord-cmd  -i/data/chord/job/input -o/data/chord/job/output
                
            -   name: chord-web-boot
                run: docker run --rm -p9999:9999 -v $PWD/zero/devops/chord:/data/chord  chord ./chord-web
                
            -   name: chord-web-boot-wait
                run: |
                    sleep 10
    
            -   name: chord-web-test
                run: |
                    curl -X POST --location "http://127.0.0.1:9999/job/exec/"  -H "Content-Type: application/json" -d "{ \"git_url\": \"git@github.com:bit-ranger/chord.git\", \"branch\": \"master\"  }"

            -   name: chord-web-test-wait
                run: |
                    sleep 30

            -   name: chord-web-test-report
                run: |
                    curl -X GET --location "http://127.0.0.1:9200/chord@bit-ranger@github.com/_search" \
                        -H "Content-Type: application/json" \
                        -d "{
                            \"query\": {
                                  \"match\": {
                                        \"layer\": \"task\"
                                  }
                            }
                            }"



    linux:
        needs: docker
        runs-on: ubuntu-latest
    
        steps:
            -   name: checkout
                uses: actions/checkout@v2
        
            -   name: build
                run: |
                    cargo build --verbose --release
        
            -   name: upload
                uses: actions/upload-artifact@v2
                with:
                    name: linux-release
                    retention-days: 1
                    if-no-files-found: error
                    path: |
                        target/release/chord-cmd
                        target/release/chord-web

    windows:
        needs: docker
        runs-on: windows-latest

        steps:
            -   name: checkout
                uses: actions/checkout@v2

            -   name: build
                run: cargo build --verbose --release

            -   name: upload
                uses: actions/upload-artifact@v2
                with:
                    name: windows-release
                    retention-days: 1
                    if-no-files-found: error
                    path: |
                        target/release/chord-cmd.exe
                        target/release/chord-web.exe

    macos:
        needs: docker
        runs-on: macos-latest

        steps:
            -   name: checkout
                uses: actions/checkout@v2

            -   name: build
                run: cargo build --verbose --release

            -   name: upload
                uses: actions/upload-artifact@v2
                with:
                    name: macos-release
                    retention-days: 1
                    if-no-files-found: error
                    path: |
                        target/release/chord-cmd
                        target/release/chord-web
