name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Compose services
        run: docker-compose up -d
      - name: Check health
        run: docker run container:chord-web curl http://localhost:9999/
