name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install curl
        run: docker pull appropriate/curl
      - name: Compose services
        run: docker-compose up -d
      - name: Check health
        run: docker run --network container:chord-web appropriate/curl -s --retry 10 --retry-connrefused http://localhost:9999/
