name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Boot services
      run: docker-compose up -d
    - name: Run job
      run: docker run --network container:chord-web appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/
