name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Boot services
        run: docker-compose -f .github/docker-compose.yml up -d
      - name: Check chord-web health
        run: docker run --network container:chord-web appropriate/curl -s --retry 10 --retry-connrefused http://127.0.0.1:9999/
      - name: Test chord-cmd
        run: docker run chord:1 ./chord-cmd -i/data/chord/job/input -o/data/chord/job/output
